paths:
  /categories:
    get:
      tags: [Categories]
      summary: Ottiene tutte le categorie
      responses:
        200:
          description: Lista delle categorie
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryBasic'
    post:
      tags: [Categories]
      summary: Crea una nuova categoria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        201:
          description: Categoria creata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryBasic'
        400:
          description: Categoria esistente o dati non validi

  /categories/{id}:
    get:
      tags: [Categories]
      summary: Ottiene una categoria per ID
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Categoria trovata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryBasic'
        404:
          description: Categoria non trovata
    put:
      tags: [Categories]
      summary: Aggiorna una categoria
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        200:
          description: Categoria modificata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryBasic'
        400:
          description: Nome già esistente o dati non validi
        404:
          description: Categoria non trovata
    delete:
      tags: [Categories]
      summary: Elimina una categoria
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        204:
          description: Cancellato con successo
        404:
          description: Categoria non trovata

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer
  schemas:
    CategoryBasic:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "pizzeria"
    CategoryInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "pizzeria"